### ISSUE TITLE
Click on DragSource prevents onblur of AjaxEditableLabel

### ISSUE THREAD

**Issue by RobAu** [svenmeier/wicket-dnd#10]
When I have a AjaxEditableLabel (wicketstuff), clicking on a DragSource prevents the onblur of the AjaxEditableLabel. What I would expect, is that the onblur is still fired.

See for a quickstart here: http://audenaerde.org/testdnd.zip

**Comment by RobAu** [comment]
Adding 
```javascript
$(':focus').blur(); 
```
in line 27 of wicket-dnd.js migitates the issue.

**Comment by svenmeier** [comment]
Thanks for reporting this issue and the fix.

**Comment by RobAu** [comment]
Thanks for the quick fix :)
