### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hypery2k** [svenmeier/wicket-dnd#13]
are there any plans to release a new version? Would be create to not need to include a SNAPSHOT-dependency ;)

**Comment by svenmeier** [comment]
I'm will release a new version in July. We'll keep this issue as a reminder.

**Comment by aaime** [comment]
Hi, is a wicket 7 compatible release going to be made available any time soon? :-)

**Comment by svenmeier** [comment]
wicket-dnd 0.7.1 is deployed and will be available in the repositories soon.
