### ISSUE TITLE
Prevent Drag on text selection

### ISSUE THREAD

**Issue by d2a-raudenaerde** [svenmeier/wicket-dnd#18]
I'd like to still be able to select text in an element that has dnd. Basically, my ideal setup would be to have a DIV with Drag, but disable Drag for all the SPANs with a certain class that on the DIV.

Is that currently (im)possible?

**Comment by svenmeier** [comment]
There is no direct support for this in the library.

Please try adding your own event handler on the spans to stop propagation:

$('dragSource').on('mousedown', 'span', function(ev){
   ev.stopPropagation();
});

This handler has to be added before the one from the dragSource. I'm not sure whether this works, perhaps you have to use stopImmediatePropagation() instead.

**Comment by d2a-raudenaerde** [comment]
Than you Sven for the suggestion!

However, after some more thinking, I think it would be nice if the dnd is initiated after a long mouse down instead of directly after mousedown. So dnd should start if the user presses long (he will see the element being cloned, which is nice feedback that it is working), else it will just fall through and do the normal behaviour (either click (no move) or select (mousedown - drag - mouseup).

**Comment by svenmeier** [comment]
Hi Rob,

we could make the JavaScript configurable with an arbitrary initiating event, defaulting to "mousedown". This way you can write your own "long press" handler, e.g. https://github.com/vaidik/longpress.js

WDYT?

**Comment by d2a-raudenaerde** [comment]
Ah, that seems a good way to do it. Perhaps similar to Wicket `AjaxEventBehaviour(String event)` constructor on DragSource?

**Comment by svenmeier** [comment]
Instead of implementing another drag gesture, I improved wicket-dnd.js with a hook method:
By monkey-patching wicketdnd.gesture(event, onDetected) users can implement their own special gesture detection, e.g. one that works with a timeout instead of a distance.

**Comment by d2a-raudenaerde** [comment]
Thanks Sven, I'll take at look at it!
