### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by ckuehne** [svenmeier/wicket-dnd#20]
Hi, 

I am trying to figure out which dnd solution to chose for my wicket project. Is wicket-dnd still maintained? Will there be a release for wicket 8?

**Comment by d2a-raudenaerde** [comment]
I use this dnd solution. Works very nicely.

**Comment by svenmeier** [comment]
wicket-dnd 7.x works fine with Wicket 8.x, there's no need for a new release.

Only wicket-dnd-examples will have to be adjusted to some recent changes in Wicket.

Note that wicket-dnd is heavily optimized for traditional *desktop-like* DnD - it may not meet all fancy effects delivered by most other JavaScript centric solutions.
