### ISSUE TITLE
Multiple DropTargets per Component

### ISSUE THREAD

**Issue by ckuehne** [svenmeier/wicket-dnd#21]
I would like to configure a wicket tree as a drop target for 

1. other tree elements for center, top, and bottom drops:
   `.dropCenter("span.tree-content, div.treeContainer").dropTopAndBottom("div.tree-branch"));`
2. list elements for center drops only
   `.dropCenter("span.tree-content, div.treeContainer"));`

This does not work currently, since dnd.dropTarget registers the drop function with the component `id` as key `$(element).data(wicketdnd.DROP_TARGET_PREFIX + id, {...`.

Is there a simple way to achieve this?

Update: As a workaround, I have added a `dropContainer` as a parent of the tree that serves as the second drop target.

**Comment by svenmeier** [comment]
Yes, you're right.

This was supposed to be improved with #9, but apparently I was mentally absent when I pushed that change.

I'll publish a new version asap.

**Comment by svenmeier** [comment]
Snapshot is fixed now.
