### ISSUE TITLE
Multiple DragTargets

### ISSUE THREAD

**Issue by Paul-MS** [svenmeier/wicket-dnd#9]
I try to setup a linking-feature using wicket-dnd and wicket-tree. Type A can be connected with type B and type B with type A. If I add only one DragSource and one DragTarget everything works fine except that I can connect type A with A and B with B. Therefore I added two Sources and two Targets, with the repo-code the sources work fine, but only one of the targets responds. In order to separate the two operations I use different operations. This is connected to issuse #3

**Comment by svenmeier** [comment]
Can you provide a quickstart?

**Comment by Paul-MS** [comment]
I attached a quickstart, if you toggle the bool withSecondTarget you should see the problem.

**Comment by svenmeier** [comment]
Quickstart? Where?

**Comment by svenmeier** [comment]
wicket-dnd does not support multiple DropTargets on the same markup tag :(.

As soon as the first target is found, it decides what to do with the dragged source.

**Comment by svenmeier** [comment]
Starting with 0.7.2 dropTargets can be nested now. You can use several nested markup-containers if needed.

**Comment by svenmeier** [comment]
... and with 0.7.3 and 0.6.2 multiple dropTargets are now supported on a single markup tag.
